# Generated by Django 4.1.1 on 2022-09-06 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundoImobiliario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('setor', models.CharField(choices=[('hospital', 'Hospital'), ('hotel', 'Hotel'), ('hibrido', 'Híbrido'), ('lajes_corporativas', 'Lajes_corporativas'), ('logistica', 'Logistica'), ('outros', 'Outros'), ('residencial', 'Residencial'), ('titulos_valores_mobiliarios', 'Titulos e Valores Mobiliarios')], max_length=30)),
                ('dividend_yield_media_12m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacancia_fisica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacancia_financeira', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidades_ativos', models.IntegerField(default=0)),
            ],
        ),
    ]
